apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  selector:
    matchLabels:
      app: second-node-app
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: second-node-app
        tier: backend
    spec:
      containers:
        - name: app
          image: kevariable/second-node-app
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"