apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  selector:
    matchLabels:
      app: second-node-app
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: second-node-app
        tier: backend
    spec:
      containers:
        - name: app
          image: kevariable/second-node-app:2
          imagePullPolicy: Always # So after apply will always re-pull the specific tag or without this can have tag :latest will always pull .
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"