apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc001
spec:
  volumeName: pv001
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
