apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector:
    app: second-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  selector:
    # matchLabels:
    #   app: second-node-app
    #   tier: backend
    matchExpressions:
      - key: app
        operator: In
        values:
          - first-node-app
          - second-node-app
  replicas: 3
  template:
    metadata:
      labels:
        app: second-node-app
        tier: backend
    spec:
      containers:
        - name: app
          image: kevariable/second-node-app
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"